//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenAdmin {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvisibleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvisibleMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenAdmin.InvisibleMessages", typeof(InvisibleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://docs.xenserver.com/en-us/ ähnelt.
        /// </summary>
        public static string DOCS_URL {
            get {
                return ResourceManager.GetString("DOCS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string HELP_URL {
            get {
                return ResourceManager.GetString("HELP_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://xcp-ng.org ähnelt.
        /// </summary>
        public static string HOMEPAGE {
            get {
                return ResourceManager.GetString("HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string HTTP_LICENSES {
            get {
                return ResourceManager.GetString("HTTP_LICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://xenserver.com/buy ähnelt.
        /// </summary>
        public static string LICENSE_BUY_URL {
            get {
                return ResourceManager.GetString("LICENSE_BUY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string LICENSE_EXPIRY_WEBPAGE {
            get {
                return ResourceManager.GetString("LICENSE_EXPIRY_WEBPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://docs.citrix.com/en-us/licensing/current-release/license-server-getting-started.html ähnelt.
        /// </summary>
        public static string LICENSE_SERVER_DOCS_LINK {
            get {
                return ResourceManager.GetString("LICENSE_SERVER_DOCS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string LICENSE_SERVER_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("LICENSE_SERVER_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en-US ähnelt.
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://xcp-ng.org ähnelt.
        /// </summary>
        public static string PLUGINS_URL {
            get {
                return ResourceManager.GetString("PLUGINS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://docs.xenserver.com/en-us/xencenter/current-release/whats-new.html ähnelt.
        /// </summary>
        public static string RELEASE_NOTES_URL {
            get {
                return ResourceManager.GetString("RELEASE_NOTES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://xcp-ng.com ähnelt.
        /// </summary>
        public static string SUPPORT_URL {
            get {
                return ResourceManager.GetString("SUPPORT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_TRIAL {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_TRIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string UPSELL_SA {
            get {
                return ResourceManager.GetString("UPSELL_SA", resourceCulture);
            }
        }
    }
}
